/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package quotes;

import com.google.gson.Gson;

import javax.net.ssl.HttpsURLConnection;
import java.io.*;
import java.net.HttpURLConnection;
import java.net.MalformedURLException;
import java.net.URL;


public class App {
    public static void main(String[] args) throws FileNotFoundException {
        
        URL url = null;
        try{
            url = new URL("http://ron-swanson-quotes.herokuapp.com/v2/quotes");
        } catch(MalformedURLException e){
            System.out.println("the URL format not formatted correctly");
            return;
        }

        try{
            HttpURLConnection connection = (HttpURLConnection) url.openConnection();
            BufferedReader in = new BufferedReader(
                    new InputStreamReader(connection.getInputStream())
            );
            String currentLine = in.readLine();
            while(currentLine != null){
                System.out.println(currentLine);
                currentLine = in.readLine();
            }
        } catch (IOException e) {
            System.out.println("The Internet no work");
            e.printStackTrace();
        }


//        Using JSON quotes / works for no Internet
        Gson gson = new Gson();

        Quote[] parseSourceQuotes = gson.fromJson(new FileReader("resources/recentquotes.json"), Quote[].class);


        int index = randomizer(parseSourceQuotes.length);
        Quote randquote = parseSourceQuotes[index];
        System.out.println(randquote);

    }


    public static int randomizer(int max){
        int x = (int)(Math.random() * max);
        return x;
    }

}
